### ISSUE TITLE
[Troubleshoot page] 9kmmrbot notice 

### ISSUE THREAD

**Issue by Aluerie** [dotabod/frontend#105]
*Just typing out DM-conversation we had long ago about my another weird idea.*

Question "Can I still use 9kmmrbot?" currently has a bit bullish/hate answer. And to add more reasoning to it we can type that 

- [ ] 9kmmrbot does not work anymore for accounts that 
  * are outside of top100 mmr live matches AND
  * game details steam profile setting set to `Private`
  
  which is probably a lot of userbase. 
- [ ] the bot worked in the first place due to a bug in Valve rich presence (getting private data nevertheless) which was fixed September 2022 and dotabod gonna stand strong bcs GSI doesn't go anywhere (and safe to use).

In total exodia theory, printing this "publicly" can spread more positivity about dotabod and explain to folks why 9kmmrbot doesn't work anymore if you are private + below high immortal.

**Comment by Geczy** [comment]
how's this?

Q: Can I still use 9kmmrbot?

A: The answer is dependent on your current MMR rank and Steam profile privacy settings. The 9kmmrbot no longer works for accounts that are outside of the top 100 MMR live matches and have their game details Steam profile setting set to "Private."

This means that if you are not in the high immortal bracket or have your Steam profile set to private, the bot will not be able to retrieve your game data. This is due to changes in the Valve rich presence system, which previously had a bug that allowed the bot to retrieve private data regardless of profile settings.

It's worth noting that this change does not affect Dotabuff's GSI integration, which is still operational and safe to use. If you are unable to use 9kmmrbot due to these changes, we recommend trying out Dotabuff's other features such as live match tracking and statistics.

We hope this information helps clarify why 9kmmrbot may no longer be working for some users and encourage you to explore other aspects of Dotabuff's services.

**Comment by dankYoff** [comment]
Many people do not pay attention to the FAQ page. If we are talking about development, then we need to move in the direction that is already in place:

### **Stage I: Attractiveness**

- Continue to run a Twitter channel
- Add a premium subscription and sometimes raffle it in social networks (subscribe, repost and like the first 5 winners will receive a free premium subscription for 2 weeks)
- Translation of the main page and dashboard
- Change UI/UX design and create a promotional video #77, #28
- Simplify the installation of the dotabod (people are afraid to install it because they do not understand how to do it correctly) #74
- Collaborations with other bots, users, etc.#25

### **Stage II: Functionality**
Add heavy and time-consuming applications to dotabod, but very cool features
1) Playing with a streamer is just awesome
2) Quiz like in Dota 2 
3) Click on Screen is a very cool thing that all people will use
This will help to increase the number of people for dotabod

**Comment by Geczy** [comment]
@dankYoff thats a new issue, there's no problem in updating the faq to fix this trivial thing

fixed btw

**Comment by Aluerie** [comment]
okay haha, it will be a mess comment like this, I dont mean to be picky for this VERY small issue. I dont even understand what danky just commented about. But all right, my further comment to your edits:

* Game Details Steam Profile setting - not necessarily Private Profile - you mistype it in 2nd paragraph
* This means that if you are not in the high immortal bracket ~~or~~ <ins>AND</ins> have your Steam profile set to private
* I dont like that you mention MMR+privacy part 2.5 times in first two paragraphs - these 3 sentences are practically same: "the bot doesn't work anymore for these and these."
* i think previous "Dotabod has all the features 9kmmrbot had, and more. " sounds more solid than your current edit "check out our other features".

**Comment by Geczy** [comment]
Perhaps something like this would work better:

9kmmrbot is no longer able to retrieve game data for accounts outside of the high immortal bracket and for those with their Dota social profile setting set to private.

This is due to changes in the Valve rich presence system, which previously had a bug that allowed the bot to retrieve private data regardless of profile settings.

It's worth noting that this change does not affect Dotabod's GSI integration, which is still operational and safe to use. If you are unable to use 9kmmrbot due to these changes, we recommend trying out Dotabod as it includes all the features 9kmmrbot had to offer and more.

We hope this information helps clarify why 9kmmrbot may no longer be working for some users and encourage you to explore other aspects of Dotabod's services.

Visit [9kmmrbot chat](https://twitch.tv/popout/9kmmrbot/chat) and type !part to remove 9kmmrbot. You may have to ban 9kmmrbot from your channel because it may keep trying to join and respond to commands still.

**Comment by Aluerie** [comment]
> Dota social profile setting

haha :D, why you... it's `Game Details` setting in `Steam Profile > Privacy Settings` the one responsible for the Rich Presence
![image](https://user-images.githubusercontent.com/33165440/222847206-56da80ab-9e76-4c1a-a2bc-3186e3e58e60.png)

* idk last paragraph still sounds disconnected to me, like we talking about good things for the dotabod and randomly drop "hey you visit and type !part"

**Comment by Geczy** [comment]
> > Dota social profile setting
> 
> haha :D, why you... it's `Game Details` setting in `Steam Profile > Privacy Settings` the one responsible for the Rich Presence ![image](https://user-images.githubusercontent.com/33165440/222847206-56da80ab-9e76-4c1a-a2bc-3186e3e58e60.png)
> 
> * idk last paragraph still sounds disconnected to me, like we talking about good things for the dotabod and randomly drop "hey you visit and type !part"

oh ive never seen this setting
